//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damasio34.SGP.Dominio.ModuloTrabalho.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Damasio34.SGP.Dominio.ModuloTrabalho.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data informada é inválida..
        /// </summary>
        internal static string DataInvalida {
            get {
                return ResourceManager.GetString("DataInvalida", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O tipo de lançamento incorreto para a operação solicitada..
        /// </summary>
        internal static string TipoDeLancamentoIncorreto
        {
            get
            {
                return ResourceManager.GetString("TipoDeLancamentoIncorreto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor do lançamento não pode ser igual a zero..
        /// </summary>
        internal static string ValorLancamentoIgualZero
        {
            get
            {
                return ResourceManager.GetString("ValorLancamentoIgualZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor do lançamento de crédito precisa ser maior que zero..
        /// </summary>
        internal static string ValorLancamentoPrecisaSerMaiorQueZero
        {
            get
            {
                return ResourceManager.GetString("ValorLancamentoPrecisaSerMaiorQueZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O valor do lançamento de débito precisa ser menor que zero..
        /// </summary>
        internal static string ValorLancamentoPrecisaSerMenorQueZero
        {
            get
            {
                return ResourceManager.GetString("ValorLancamentoPrecisaSerMenorQueZero", resourceCulture);
            }
        }
    }
}
